### ISSUE TITLE
konnichiwa

### ISSUE THREAD

**Issue by halukmy** [tengge1/learn-tensorflow-sharp#1]
thanks for share
arigato
do you have any contact information data?,,
im so happy if you can mail me halukmy@gmail.com

or whatsapp +90 507 0 44 3 888

thanks sensei

**Comment by tengge1** [comment]
Hello, @halukmy 

Sorry for replying you late.
I think the best way to contact me is through github.
The words is Chinese, not Japanese.
Keep in touch.

Best Regards,
tengge1

**Comment by halukmy** [comment]
thanks @tengge1  i cant wait your shares

best wishes with you
