### ISSUE TITLE
关于第六课LR回归的教程疑问

### ISSUE THREAD

**Issue by zhanglifan1022** [tengge1/learn-tensorflow-sharp#6]
你好，首先非常感谢你关于tensorsharp的教程，我上网找了大半圈都没找到任何别的资源，直到来到你这里，受益匪浅！

你设定了一个线性的公式去随机生成训练集，但是我有两个疑问：
1. 为什么AddGradient里面的参数b并没有根据loss更新？
2.为什么每次喂数据，都是直接一个xData列表塞进去而不是xData[i]一组组数据塞进去呢？这两者有没有区别？

非常感谢！

**Comment by tengge1** [comment]
不好意思，直接抄的官方测试demo，没仔细研究过。
